name: AAPS CI

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'FullRelease'
        type: choice
        options:
          - FullRelease
          - FullDebug
          - aapsclientRelease
          - aapsclientDebug
          - aapsclient2Release
          - aapsclient2Debug
          - pumpcontrolRelease
          - pumpcontrolDebug
      uploadTarget:
        description: 'Select Upload Target'
        required: true
        default: 'dropbox'
        type: choice
        options:
          - dropbox

jobs:
  build:
    name: Build AAPS
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          MISSING=0
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "❌ Missing secret: KEYSTORE_BASE64"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
            echo "❌ Missing secret: KEYSTORE_PASSWORD"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
            echo "❌ Missing secret: KEY_ALIAS"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "❌ Missing secret: KEY_PASSWORD"
            MISSING=1
          fi
          if [ "${{ github.event.inputs.uploadTool }}" = "dropbox" ]; then
            if [ -z "${{ secrets.DROPBOX_ACCESS_TOKEN }}" ]; then
              echo "❌ Missing secret: DROPBOX_ACCESS_TOKEN (required for Dropbox upload)"
              echo ""
              echo "🔧 Please create an app and generate a token at:"
              echo "👉 https://www.dropbox.com/developers/apps"
              echo ""
              echo "📘 For detailed instructions, see:"
              echo "🔗 https://androidaps.readthedocs.io/en/latest/SettingUpAaps/BuildingAaps.html#upload-to-dropbox"
              MISSING=1
            fi
          fi
          if [ "$MISSING" -eq 1 ]; then
            echo "🛑 One or more required secrets are missing. Failing the build."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set BUILD_VARIANT
        run: |
          BUILD_VARIANT="${{ github.event.inputs.buildVariant }}"
          echo "BUILD_VARIANT=$BUILD_VARIANT" >> $GITHUB_ENV
          echo "Selected BUILD_VARIANT: $BUILD_VARIANT"

          VARIANT_FLAVOR=$(echo "$BUILD_VARIANT" | sed -E 's/(Release|Debug)$//' | tr '[:upper:]' '[:lower:]')
          VARIANT_TYPE=$(echo "$BUILD_VARIANT" | grep -oE '(Release|Debug)$' | tr '[:upper:]' '[:lower:]')

          echo "VARIANT_FLAVOR=$VARIANT_FLAVOR" >> $GITHUB_ENV
          echo "VARIANT_TYPE=$VARIANT_TYPE" >> $GITHUB_ENV
          echo "VARIANT_FLAVOR: $VARIANT_FLAVOR"
          echo "VARIANT_TYPE: $VARIANT_TYPE"

          VERSION_SUFFIX=""
          if [[ "$VARIANT_FLAVOR" != "full" ]]; then
            VERSION_SUFFIX="$VARIANT_FLAVOR"
          fi
          if [[ "$VARIANT_TYPE" == "debug" ]]; then
            VERSION_SUFFIX="$VERSION_SUFFIX-debug"
          fi
          if [[ -n "$VERSION_SUFFIX" && "$VERSION_SUFFIX" != -* ]]; then
            VERSION_SUFFIX="-$VERSION_SUFFIX"
          fi
          echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
          echo "VERSION_SUFFIX: $VERSION_SUFFIX"

      - name: Extract VERSION_NAME for App and Wear
        run: |
          BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
          if echo "$BRANCH_NAME" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'; then
            VERSION="$BRANCH_NAME"
            echo "🔢 Using branch version as version: $BRANCH_NAME"
          else
            VERSION=$(grep 'val appVersion' buildSrc/src/main/kotlin/Versions.kt | awk -F '"' '{print $2}')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION: $VERSION"

      - name: Map JDK version by app version
        run: |
          case "$VERSION" in
            2.6.2) JDK_VERSION="11" ;;
            2.8.2.1) JDK_VERSION="17" ;;
            3.1.0.3) JDK_VERSION="17" ;;
            3.2.0.4) JDK_VERSION="19" ;;
            3.3.*) JDK_VERSION="21" ;;
            *)
              echo "❌ Unsupported app version: $VERSION"
              exit 1
              ;;
          esac
          echo "JDK_VERSION=$JDK_VERSION" >> $GITHUB_ENV
          echo "📦 App Version: $VERSION → JDK Version: $JDK_VERSION"
          echo "jdk_version=$JDK_VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Decode keystore
        run: |
          mkdir -p "$RUNNER_TEMP/keystore"
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > "$RUNNER_TEMP/keystore/keystore.jks"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APKs
        run: |
          ./gradlew assemble${{ env.BUILD_VARIANT }} \
          -Pandroid.injected.signing.store.file="$RUNNER_TEMP/keystore/keystore.jks" \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename APKs with version
        run: |
          mv app/build/outputs/apk/${{ env.VARIANT_FLAVOR }}/${{ env.VARIANT_TYPE }}/*.apk \
            aaps-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk

          mv wear/build/outputs/apk/${{ env.VARIANT_FLAVOR }}/${{ env.VARIANT_TYPE }}/*.apk \
            aaps-wear-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk

      - name: Upload APKs to Target
        run: |
          set -e
          if [[ "${{ github.event.inputs.uploadTarget }}" == "dropbox" ]]; then
            RESPONSE=$(curl -s -X POST https://api.dropbox.com/oauth2/token \
              -u "${{ secrets.DROPBOX_APP_KEY }}:${{ secrets.DROPBOX_APP_SECRET }}" \
              -d grant_type=refresh_token \
              -d refresh_token=${{ secrets.DROPBOX_REFRESH_TOKEN }})
  
            ACCESS_TOKEN=$(echo "$RESPONSE" | jq -r .access_token)
            echo "::add-mask::$ACCESS_TOKEN"
            echo "access_token=$ACCESS_TOKEN" >> $GITHUB_ENV
          
            upload_to_dropbox() {
              FILE_PATH=$1
              DROPBOX_DEST=$2
              if [ ! -f "$FILE_PATH" ]; then
                echo "❌ File not found: $FILE_PATH"
                exit 1
              fi
              echo "⬆️ Uploading $FILE_PATH to Dropbox as $DROPBOX_DEST..."
              RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/response.json \
                -X POST https://content.dropboxapi.com/2/files/upload \
                --header "Authorization: Bearer $ACCESS_TOKEN" \
                --header "Dropbox-API-Arg: {\"path\": \"/$DROPBOX_DEST\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false}" \
                --header "Content-Type: application/octet-stream" \
                --data-binary @"$FILE_PATH")
              HTTP_CODE="${RESPONSE: -3}"
              if [[ "$HTTP_CODE" != "200" ]]; then
                echo "❌ Upload failed with HTTP status: $HTTP_CODE"
                cat /tmp/response.json
                exit 1
              fi
              echo "✅ Upload successful: $DROPBOX_DEST"
            }
            upload_to_dropbox "aaps-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk" "${{ env.VERSION }}/aaps-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk"
            upload_to_dropbox "aaps-wear-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk" "${{ env.VERSION }}/aaps-wear-${{ env.VERSION }}${{ env.VERSION_SUFFIX }}.apk"
          fi