name: AAPS CI

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'FullRelease'
        type: choice
        options:
          - FullRelease
          - FullDebug
          - aapsclientRelease
          - aapsclientDebug
          - aapsclient2Release
          - aapsclient2Debug
          - pumpcontrolRelease
          - pumpcontrolDebug
      uploadTarget:
        description: 'Select Upload Target'
        required: true
        default: 'dropbox'
        type: choice
        options:
          - dropbox

jobs:
  build:
    name: Build AAPS
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          MISSING=0
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "❌ Missing secret: KEYSTORE_BASE64"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
            echo "❌ Missing secret: KEYSTORE_PASSWORD"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then
            echo "❌ Missing secret: KEY_ALIAS"
            MISSING=1
          fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "❌ Missing secret: KEY_PASSWORD"
            MISSING=1
          fi

          # Conditionally check Dropbox secret if uploadTool is dropbox
          if [ "${{ github.event.inputs.uploadTool }}" = "dropbox" ]; then
            if [ -z "${{ secrets.DROPBOX_ACCESS_TOKEN }}" ]; then
              echo "❌ Missing secret: DROPBOX_ACCESS_TOKEN (required for Dropbox upload)"
              echo ""
              echo "🔧 Please create an app and generate a token at:"
              echo "👉 https://www.dropbox.com/developers/apps"
              echo ""
              echo "📘 For detailed instructions, see:"
              echo "🔗 https://androidaps.readthedocs.io/en/latest/SettingUpAaps/BuildingAaps.html#upload-to-dropbox"
              MISSING=1
            fi
          fi

          if [ "$MISSING" -eq 1 ]; then
            echo "🛑 One or more required secrets are missing. Failing the build."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v4

