name: Android CI

on:
  push:
    branches: [ "release-*" ]
  pull_request:
    branches: [ "release-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
            ./gradlew assembleRelease \
            -PstorePassword=${{ secrets.STORE_PASSWORD }} \
            -PkeyAlias=${{ secrets.KEY_ALIAS }} \
            -PkeyPassword=${{ secrets.KEY_PASSWORD }} \
            -PstoreFile=${{ secrets.STORE_FILE }}
      - name: Extract VERSION_NAME
        id: extract_version
        run: |
          VERSION=$(grep 'VERSION_NAME' app/build/generated/source/buildConfig/full/release/app/aaps/BuildConfig.java | awk -F '"' '{print $2}')
          echo "version_name=$VERSION" >> $GITHUB_OUTPUT
      - name: Rename APK with version
        run: |
          mv app/build/outputs/apk/full/release/app-full-release.apk aaps-${{ steps.extract_version.outputs.version_name }}.apk
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aaps-${{ steps.extract_version.outputs.version_name }}.apk
          path: aaps-${{ steps.extract_version.outputs.version_name }}.apk