name: Android CI

on:
  push:
    branches: ["release-*"]
  pull_request:
    branches: ["release-*"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      buildVariant:
        description: 'Select Build Variant'
        required: true
        default: 'FullRelease'
        type: choice
        options:
          - FullRelease
          - FullDebug
          - aapsclientRelease
          - aapsclientDebug
          - aapsclient2Release
          - aapsclient2Debug
          - pumpcontrolRelease
          - pumpcontrolDebug

env:
  DEFAULT_BUILD_VARIANT: FullRelease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Decode keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $(pwd)/keystore/keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set BUILD_VARIANT (default if empty)
        id: set_build_variant
        run: |
          if [[ -n "${{ github.event.inputs.buildVariant }}" ]]; then
            BUILD_VARIANT="${{ github.event.inputs.buildVariant }}"
          else
            BUILD_VARIANT="${{ env.DEFAULT_BUILD_VARIANT }}"
          fi
          echo "BUILD_VARIANT=$BUILD_VARIANT" >> $GITHUB_ENV
          echo "Selected BUILD_VARIANT: $BUILD_VARIANT"

      - name: Build APKs
        run: |
          ./gradlew assemble${{ env.BUILD_VARIANT }} \
          -Pandroid.injected.signing.store.file=$(pwd)/keystore/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Extract VERSION_NAME for App and Wear
        id: extract_versions
        run: |
          VARIANT_LOWER=$(echo "${{ env.BUILD_VARIANT }}" | tr '[:upper:]' '[:lower:]')
          APP_VERSION=$(grep 'VERSION_NAME' app/build/generated/source/buildConfig/$VARIANT_LOWER/app/aaps/BuildConfig.java | awk -F '"' '{print $2}')
          WEAR_VERSION=$(grep 'VERSION_NAME' wear/build/generated/source/buildConfig/$VARIANT_LOWER/app/wear/BuildConfig.java | awk -F '"' '{print $2}' | head -n 1)
          
          echo "app_version_name=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "wear_version_name=$WEAR_VERSION" >> $GITHUB_OUTPUT
          
          echo "App VERSION_NAME: $APP_VERSION"
          echo "Wear VERSION_NAME: $WEAR_VERSION"

      - name: Rename APKs with version
        run: |
          VARIANT_LOWER=$(echo "${{ env.BUILD_VARIANT }}" | tr '[:upper:]' '[:lower:]')
          mv app/build/outputs/apk/$VARIANT_LOWER/*.apk aaps-${{ env.BUILD_VARIANT }}-${{ steps.extract_versions.outputs.app_version_name }}.apk
          mv wear/build/outputs/apk/$VARIANT_LOWER/*.apk aaps-wear-${{ env.BUILD_VARIANT }}-${{ steps.extract_versions.outputs.wear_version_name }}.apk

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aaps-${{ env.BUILD_VARIANT }}-${{ steps.extract_versions.outputs.app_version_name }}
          path: |
            aaps-${{ env.BUILD_VARIANT }}-${{ steps.extract_versions.outputs.app_version_name }}.apk
            aaps-wear-${{ env.BUILD_VARIANT }}-${{ steps.extract_versions.outputs.wear_version_name }}.apk